import type { AssetAnalysis, Candle, MarketSnapshot, PriceZone, PullbackAnalysis, TechnicalAnalysis } from '../models';
import { bollinger, ema, rsi } from './indicators';

export function detectZones(candles:Candle[]):PriceZone[]{
  const range=Math.max(...candles.map(c=>c.high))-Math.min(...candles.map(c=>c.low)); const tolerance=range*.025||.00001; const pivots=candles.flatMap((c,i,a)=>[
    ...(i>0&&i<a.length-1&&c.low<=a[i-1].low&&c.low<=a[i+1].low?[{price:c.low,type:'support' as const}]:[]),
    ...(i>0&&i<a.length-1&&c.high>=a[i-1].high&&c.high>=a[i+1].high?[{price:c.high,type:'resistance' as const}]:[])]);
  const groups:{type:'support'|'resistance';prices:number[]}[]=[]; for(const p of pivots){const g=groups.find(x=>x.type===p.type&&Math.abs(x.prices.reduce((a,b)=>a+b,0)/x.prices.length-p.price)<=tolerance); g?g.prices.push(p.price):groups.push({type:p.type,prices:[p.price]});}
  return groups.map(g=>({type:g.type,min:Math.min(...g.prices)-tolerance/2,max:Math.max(...g.prices)+tolerance/2,touches:g.prices.length,strength:Math.min(100,25+g.prices.length*20)})).sort((a,b)=>b.strength-a.strength);
}
export function detectPatterns(candles:Candle[]):string[]{const c=candles.at(-1),p=candles.at(-2);if(!c)return[];const body=Math.abs(c.close-c.open),range=c.high-c.low||1,upper=c.high-Math.max(c.open,c.close),lower=Math.min(c.open,c.close)-c.low,out:string[]=[];if(body/range<.12)out.push('doji','candle de indecisão');if(lower>body*2&&upper<body)out.push('martelo','pavio inferior relevante');if(upper>body*2&&lower<body)out.push('shooting star','pavio superior relevante');if(body/range>.7)out.push('candle de força');if(p&&c.close>c.open&&p.close<p.open&&c.open<=p.close&&c.close>=p.open)out.push('bullish engulfing');if(p&&c.close<c.open&&p.close>p.open&&c.open>=p.close&&c.close<=p.open)out.push('bearish engulfing');return out;}
function trendOf(c:Candle[],e9:number,e20:number,e50:number){const momentum=(c.at(-1)?.close??0)-(c.at(-6)?.close??0);const aligned=e9>e20&&e20>e50?1:e9<e20&&e20<e50?-1:0;const direction=momentum>0?1:momentum<0?-1:0;const n=aligned+direction;return n===2?'forte alta':n===1?'alta':n===-1?'baixa':n===-2?'forte baixa':'lateral';}
export function detectPullback(c:Candle[],trend:string,zones:PriceZone[]):PullbackAnalysis {const dir=trend.includes('alta')?'up':trend.includes('baixa')?'down':'neutral';if(dir==='neutral')return{detected:false,trendDirection:dir,stage:'invalidated',confidence:20};const last=c.at(-1)!,prev=c.at(-2)!;const correction=dir==='up'?last.close<prev.close:last.close>prev.close;const relevant=zones.filter(z=>z.type===(dir==='up'?'support':'resistance')).sort((a,b)=>Math.abs(last.close-(a.min+a.max)/2)-Math.abs(last.close-(b.min+b.max)/2))[0];const near=!!relevant&&last.close>=relevant.min-(relevant.max-relevant.min)*2&&last.close<=relevant.max+(relevant.max-relevant.min)*2;return{detected:correction||near,trendDirection:dir,stage:near?'approaching-zone':correction?'pullback-starting':'impulse',targetZone:relevant,confidence:near?75:correction?60:40};}
export function analyze(snapshot:MarketSnapshot):AssetAnalysis{const closes=snapshot.candles.map(c=>c.close),e9=ema(closes,9),e20=ema(closes,20),e50=ema(closes,50),trend=trendOf(snapshot.candles,e9,e20,e50),zones=detectZones(snapshot.candles),patterns=detectPatterns(snapshot.candles),pullback=detectPullback(snapshot.candles,trend,zones),bb=bollinger(closes),rv=rsi(closes),last=snapshot.candles.at(-1)!,avg=snapshot.candles.slice(-20).reduce((s,c)=>s+Math.abs(c.close-c.open),0)/20,extended=Math.abs(last.close-last.open)>avg*2;let bias:'ABOVE'|'BELOW'|'WAIT'=trend.includes('alta')?'ABOVE':trend.includes('baixa')?'BELOW':'WAIT';let score=trend.startsWith('forte')?4:trend==='lateral'?2:3;const reasons=[`tendência ${trend}`,`RSI ${rv.toFixed(0)}`,`Bollinger: ${bb.position}`];let warning;if(extended){bias='WAIT';score=Math.max(1,score-2);warning='Movimento esticado: entrada atrasada. ESPERAR pullback.';reasons.push('regra de não perseguir movimento');}else if(pullback.detected){score=Math.min(5,score+1);reasons.push('pullback em desenvolvimento');}if(rv>75||rv<25){score=Math.max(1,score-1);reasons.push('RSI em região extrema');}const technical:TechnicalAnalysis={ema9:e9,ema20:e20,ema50:e50,rsi:rv,rsiState:rv>70?'overbought':rv<30?'oversold':'neutral',bollinger:bb,trend,zones,patterns,pullback};const support=zones.filter(z=>z.type==='support').sort((a,b)=>Math.abs(snapshot.currentPrice-a.max)-Math.abs(snapshot.currentPrice-b.max))[0],resistance=zones.filter(z=>z.type==='resistance').sort((a,b)=>Math.abs(snapshot.currentPrice-a.min)-Math.abs(snapshot.currentPrice-b.min))[0];return{symbol:snapshot.symbol,score:score as 1|2|3|4|5,bias,trend,currentPrice:snapshot.currentPrice,primarySupport:support,primaryResistance:resistance,entryZone:pullback.targetZone&&{min:pullback.targetZone.min,max:pullback.targetZone.max},pullback,reasons,warning,generatedAt:Date.now(),technical};}
